### ISSUE TITLE
Two Swiper components on the same page control eachother

### ISSUE THREAD

**Issue by Shpadoinkle** [sonaye/react-native-animated-swiper#4]
Currently using two swiper components on the same page to view two different sets on data.

Swiping one Swiper component changes the highlighted dot on the other Swiper component and vice versa. 

Is there a props they share?  or is there a ways to use a different parameter name for dot highlight?

**Comment by sonaye** [comment]
That shouldn't happen, can you share some code?

**Comment by Shpadoinkle** [comment]
I dont the same code right now but it was basically along the lines of

```
<ScrollView>
   <Swiper> //Swiper 1
      <Item>
      <Item>
      <Item>
   </Swiper>
   <View>
      Other random things in page
   </View>
   <Swiper>  //Swiper 2
      <Item>
      <Item>
      <Item>
   </Swiper>
</ScrollView>
```

When i swiped the top swiper.. the top swiper acted as expected, the dot would update to the appropriate index.. but the bottom swiper would update it's dots as well to the same index as the top swiper (the actual swipable items didnt move, just the dots)

**Comment by sonaye** [comment]
Ah, that's because you are using the same driver for both swipers (offered in defaultProps). You can pass your own drivers to avoid that.

```js
<Swiper driver={new Animated.Value(0)} />
<Swiper driver={new Animated.Value(0)} />
```

**Comment by Shpadoinkle** [comment]
Sweet thanks for that.
